export const API_ROUTES = {
  ACCOUNTING: '/api/accounting',
  ADT: '/api/adt',
  APPOINTMENT: '/api/appointment',
  AUTH: '/api/auth',
  BILLING: '/api/billing',
  CLAIM_MGMT: '/api/claim-mgmt',
  CLINICAL: '/api/clinical',
  CLINICAL_SETTINGS: '/api/clinical-settings',
  CSSD: '/api/cssd',
  DASHBOARD: '/api/dashboard',
  DISPENSARY: '/api/dispensary',
  DOCTOR: '/api/doctor',
  DYNAMIC_REPORT: '/api/dynamic-report',
  EMERGENCY: '/api/emergency',
  FIXED_ASSETS: '/api/fixed-assets',
  HELPDESK: '/api/helpdesk',
  INCENTIVE: '/api/incentive',
  INVENTORY: '/api/inventory',
  LABORATORY: '/api/laboratory',
  MATERNITY: '/api/maternity',
  MEDICAL_RECORDS: '/api/medical-records',
  MKT_REFERRAL: '/api/mkt-referral',
  NHIF: '/api/nhif',
  NURSING: '/api/nursing',
  OPERATION_THEATRE: '/api/operation-theatre',
  PATIENT: '/api/patient',
  PHARMACY: '/api/pharmacy',
  PROCUREMENT: '/api/procurement',
  QUEUE_MNGMT: '/api/queue-mngmt',
  RADIOLOGY: '/api/radiology',
  REPORTS: '/api/reports',
  SETTINGS: '/api/settings',
  SOCIAL_SERVICE: '/api/social-service',
  SUBSTORE: '/api/substore',
  SYSTEM_ADMIN: '/api/system-admin',
  UTILITIES: '/api/utilities',
  VACCINATION: '/api/vaccination',
  VERIFICATION: '/api/verification',
  WARD: '/api/wards',
  TRANSACTION: '/api/transaction',
  PAYROLL: '/api/payroll',
};

export const BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000';

export default { API_ROUTES, BASE_URL };