// clinical/clinicalService.js
import { API_ROUTES, BASE_URL } from '../api';

const dummyClinicalRecords = [
  {
    id: 1,
    patient: { id: 1, name: "Aisha Nakato" },
    patientType: "outpatient",
    diagnosis: "Malaria",
    date: "2025-05-01T09:00:00Z",
    notes: "Prescribed Artemether-Lumefantrine",
  },
  {
    id: 2,
    patient: { id: 2, name: "John Muwanga" },
    patientType: "outpatient",
    diagnosis: "Hypertension",
    date: "2025-05-02T10:30:00Z",
    notes: "Prescribed Amlodipine 5mg",
  },
  {
    id: 3,
    patient: { id: 3, name: "Fatuma Nansamba" },
    patientType: "inpatient",
    diagnosis: "Pneumonia",
    ipNumber: "IP2025001",
    date: "2025-05-03T14:00:00Z",
    notes: "Admitted for IV antibiotics",
  },
  {
    id: 4,
    patient: { id: 4, name: "Peter Okello" },
    patientType: "emergency",
    diagnosis: "Acute Asthma Attack",
    triageStatus: "Red",
    date: "2025-05-04T11:00:00Z",
    notes: "Nebulized with Salbutamol",
  },
  {
    id: 5,
    patient: { id: 5, name: "Mary Namusisi" },
    patientType: "outpatient",
    diagnosis: "Gastritis",
    date: "2025-05-05T15:30:00Z",
    notes: "Prescribed Omeprazole",
  },
  {
    id: 6,
    patient: { id: 6, name: "Joseph Kizito" },
    patientType: "inpatient",
    diagnosis: "Appendicitis",
    ipNumber: "IP2025002",
    date: "2025-05-06T08:00:00Z",
    notes: "Scheduled for appendectomy",
  },
  {
    id: 7,
    patient: { id: 7, name: "Esther Namaganda" },
    patientType: "outpatient",
    diagnosis: "Urinary Tract Infection",
    date: "2025-05-07T13:00:00Z",
    notes: "Prescribed Ciprofloxacin",
  },
  {
    id: 8,
    patient: { id: 8, name: "David Ssentongo" },
    patientType: "emergency",
    diagnosis: "Fractured Arm",
    triageStatus: "Yellow",
    date: "2025-05-08T16:00:00Z",
    notes: "Applied plaster cast",
  },
  {
    id: 9,
    patient: { id: 9, name: "Lillian Nakanwagi" },
    patientType: "outpatient",
    diagnosis: "Diabetes Type 2",
    date: "2025-05-09T10:00:00Z",
    notes: "Prescribed Metformin",
  },
  {
    id: 10,
    patient: { id: 10, name: "Samuel Wasswa" },
    patientType: "inpatient",
    diagnosis: "Severe Malaria",
    ipNumber: "IP2025003",
    date: "2025-05-10T12:30:00Z",
    notes: "IV Artesunate administered",
  },
  {
    id: 11,
    patient: { id: 11, name: "Grace Nabukenya" },
    patientType: "outpatient",
    diagnosis: "Allergic Rhinitis",
    date: "2025-05-11T09:30:00Z",
    notes: "Prescribed Cetirizine",
  },
  {
    id: 12,
    patient: { id: 12, name: "Moses Kizza" },
    patientType: "emergency",
    diagnosis: "Laceration on Leg",
    triageStatus: "Yellow",
    date: "2025-05-12T14:30:00Z",
    notes: "Wound sutured",
  },
  {
    id: 13,
    patient: { id: 13, name: "Ruth Namatovu" },
    patientType: "inpatient",
    diagnosis: "Postpartum Hemorrhage",
    ipNumber: "IP2025004",
    date: "2025-05-13T11:30:00Z",
    notes: "Oxytocin administered",
  },
  {
    id: 14,
    patient: { id: 14, name: "Isaac Mugerwa" },
    patientType: "outpatient",
    diagnosis: "Conjunctivitis",
    date: "2025-05-14T15:00:00Z",
    notes: "Prescribed Chloramphenicol eye drops",
  },
  {
    id: 15,
    patient: { id: 15, name: "Sarah Nankya" },
    patientType: "emergency",
    diagnosis: "Hypoglycemic Episode",
    triageStatus: "Red",
    date: "2025-05-15T08:30:00Z",
    notes: "Administered glucose IV",
  },
  {
    id: 16,
    patient: { id: 16, name: "Thomas Ssemakula" },
    patientType: "outpatient",
    diagnosis: "Skin Rash",
    date: "2025-05-16T10:00:00Z",
    notes: "Prescribed Hydrocortisone cream",
  },
  {
    id: 17,
    patient: { id: 17, name: "Jane Namubiru" },
    patientType: "inpatient",
    diagnosis: "Tuberculosis",
    ipNumber: "IP2025005",
    date: "2025-05-17T13:30:00Z",
    notes: "Started on anti-TB regimen",
  },
  {
    id: 18,
    patient: { id: 18, name: "Patrick Ssebulime" },
    patientType: "outpatient",
    diagnosis: "Hypertension",
    date: "2025-05-18T16:30:00Z",
    notes: "Prescribed Losartan",
  },
  {
    id: 19,
    patient: { id: 19, name: "Christine Nansubuga" },
    patientType: "emergency",
    diagnosis: "Severe Dehydration",
    triageStatus: "Red",
    date: "2025-05-19T09:00:00Z",
    notes: "IV fluids administered",
  },
  {
    id: 20,
    patient: { id: 20, name: "Emmanuel Kigozi" },
    patientType: "outpatient",
    diagnosis: "Dental Caries",
    date: "2025-05-20T12:00:00Z",
    notes: "Referred to dentist",
  },
];

export async function getClinicalRecords() {
  return Promise.resolve(dummyClinicalRecords);
}

export async function createClinicalRecord(data) {
  const newRecord = {
    id: dummyClinicalRecords.length + 1,
    patient: { id: parseInt(data.patientId), name: data.patientName || "Unknown" },
    patientType: data.patientType,
    diagnosis: data.diagnosis,
    date: new Date(data.date || Date.now()).toISOString(),
    notes: data.notes || "",
    ...(data.patientType === "inpatient" && { ipNumber: data.ipNumber || `IP${new Date().getFullYear()}00${dummyClinicalRecords.length + 1}` }),
    ...(data.patientType === "emergency" && { triageStatus: data.triageStatus || "Yellow" }),
  };
  dummyClinicalRecords.push(newRecord);
  return Promise.resolve(newRecord);
}