export const STATUS_OPTIONS = {
  APPOINTMENT: ['SCHEDULED', 'COMPLETED', 'CANCELLED'],
  BILL: ['PENDING', 'PAID', 'OVERDUE'],
  CLAIM: ['SUBMITTED', 'APPROVED', 'REJECTED', 'PENDING'],
  CSSD: ['PENDING', 'STERILIZED', 'USED'],
  DISPENSARY: ['PENDING', 'DISPENSED', 'CANCELLED'],
};

export const ROLES = ['ADMIN', 'DOCTOR', 'NURSE', 'PATIENT', 'STAFF'];
